# usage
# export ANSIBLE_TF_DIR=../terraform/ && ansible-playbook --vault-id ~/.ansible_vault_pass.txt -i /etc/ansible/terraform.py discovery_server.yml -e "target_env=staging security_mode=secure"

# Locally register inventory hosts
- hosts: 'localhost'
  connection: 'local'
  gather_facts: yes
  roles:
  - { role: '../../shared/ansible/roles/register_inventory_hosts' }
  - { role: 'download_consul' }

- hosts: "&{{ target_env }}:&consul-server"
  remote_user: "root"
  become: 'yes'
  roles:
  - { role: 'deploy_consul' }
  - { role: 'upgrade_consul', node_role: 'server'}

