# usage
# export ANSIBLE_TF_DIR=../terraform/ && ansible-playbook --vault-id ~/.ansible_vault_pass.txt -i /etc/ansible/terraform.py broker_server.yml -e "target_env=staging"

- hosts: "&{{ target_env }}:&broker-server"
  remote_user: "root"
  become: 'yes'
  roles:
  - { role: 'broker/upgrade_rabbitmq'}

