# usage
# export ANSIBLE_TF_DIR=../terraform/ && ansible-playbook --vault-id ~/.ansible_vault_pass.txt -i /etc/ansible/terraform.py consul_server.yml -e "target_env=staging"

# Locally register inventory hosts
- hosts: 'localhost'
  connection: 'local'
  gather_facts: yes
  roles:
  - { role: 'consul/download_consul' }

- hosts: "&{{ target_env }}:&consul-server"
  remote_user: "root"
  become: 'yes'
  roles:
  - { role: 'consul/deploy_consul' }
  - { role: 'consul/upgrade_consul', node_role: 'server'}

