# usage
# export ANSIBLE_TF_DIR=../terraform/ && ansible-playbook --vault-id ~/.ansible_vault_pass.txt -i /etc/ansible/terraform.py discovery_server.yml -e "target_env=staging"

# Locally register inventory hosts
- hosts: 'localhost'
  connection: 'local'
  gather_facts: yes
  roles:
  - { role: 'discovery/download_consul' }

- hosts: "&{{ target_env }}:&discovery-server"
  remote_user: "root"
  become: 'yes'
  roles:
  - { role: 'discovery/deploy_consul' }
  - { role: 'discovery/upgrade_consul', node_role: 'server'}

