# usage
# export ANSIBLE_TF_DIR=../terraform/ && ansible-playbook --vault-id ~/.ansible_vault_pass.txt -i /etc/ansible/terraform.py register_inventory_hosts.yml -e "target_env=staging"

# Locally register inventory hosts
- hosts: 'localhost'
  connection: 'local'
  gather_facts: yes
  roles:
  - { role: 'shared/register_inventory_hosts' }
