architecture_map:
  # this first entry seems redundant
  # (but it's required for reasons)
  amd64: 'amd64'
  x86_64: 'amd64'
  armv6l: 'arm'
  armv7l: 'arm'
  aarch64: 'arm64'
  32-bit: '386'
  64-bit: 'amd64'
os_architecture: "{{ architecture_map[ansible_architecture] }}"
os_family: "\
  {% if ansible_os_family == 'Windows' %}\
    {{ 'windows' }}\
  {% else %}\
    {{ ansible_system | lower }}\
  {% endif %}"

domain: "agileinfra.io"

htpasswd_path: '/etc/nginx/passwdfile'
