domain: "agileinfra.io"

htpasswd_path: '/etc/nginx/passwdfile'

# systemd shared vars
service_startup_timeout: 60

# consul shared vars
architecture_map:
  # this first entry seems redundant
  # (but it's required for reasons)
  amd64: 'amd64'
  x86_64: 'amd64'
  armv6l: 'arm'
  armv7l: 'arm'
  aarch64: 'arm64'
  32-bit: '386'
  64-bit: 'amd64'
os_architecture: "{{ architecture_map[ansible_architecture] }}"
os_family: "\
  {% if ansible_os_family == 'Windows' %}\
    {{ 'windows' }}\
  {% else %}\
    {{ ansible_system | lower }}\
  {% endif %}"

consul_product: 'consul'
consul_version: '1.2.3'
consul_download_dir: '/tmp/{{ consul_product }}/downloads'

consul_os_packages: ['unzip']
consul_checksum_file_url: "https://releases.hashicorp.com/{{ consul_product }}/{{ consul_version }}/{{ consul_product }}_{{ consul_version}}_SHA256SUMS"
consul_pkg: "{{ consul_product }}_{{ consul_version }}_{{ os_family }}_{{ os_architecture }}"
consul_zip_url: "https://releases.hashicorp.com/{{ consul_product }}/{{ consul_version }}/{{ consul_pkg }}.zip"
