---

- name: install openjdk 8
  apt: path={{ platform_build_dir }} state='absent'

- name: create clone dir {{ platform_build_dir }}
  file: path={{ platform_build_dir }} state='directory'

- name: clone {{ platform_repo }}
  git: repo={{ platform_repo }} dest={{ platform_clone_dir }} version={{ rev }} accept_hostkey='true'

- name: building platform located at {{ platform_clone_dir }}
  command: mvn clean install
  args:
    chdir: "{{ platform_clone_dir }}/platform"
