---
- name: create current revision dir {{ platform_home_dir }}
  file: state='directory' path="{{ platform_home_dir }}"

# unlink, re-link jar
- name: unlink {{ platform_home_dir }}/{{ backend_name }}-{{ backend_role }}.jar older revision
  file: state='absent' dest={{ platform_home_dir }}/{{ backend_name }}-{{ backend_role }}.jar
  ignore_errors: 'yes'

- name: link {{ backend_name }}-{{ backend_role }}.jar to new revision
  file: state='link' src={{ platform_deploy_home_dir }}/{{ backend_name }}-{{ backend_role }}.jar dest={{ platform_home_dir }}/{{ backend_name }}-{{ backend_role }}.jar

# unlink, update, re-link {{ backend_role }}.properties
- name: unlink {{ platform_home_dir }}/{{ backend_name }}-{{ backend_role }}.properties
  file: state='absent' dest={{ platform_home_dir }}/{{ backend_name }}-{{ backend_role }}.properties
  ignore_errors: 'yes'

- name: interpolate {{ backend_name }} properties config
  template: src={{ backend_name }}-{{ backend_role }}.properties.j2 dest={{ platform_deploy_home_dir }}/{{ backend_name }}-{{ backend_role }}.properties

- name: link {{ backend_name }}-{{ backend_role }}.properties
  file: state='link' src={{ platform_deploy_home_dir }}/{{ backend_name }}-{{ backend_role }}.properties dest={{ platform_home_dir }}/{{ backend_name }}-{{ backend_role }}.properties

# run
- name: running store example
  command: {{ platform_home_dir }}/{{ backend_name }}-{{ backend_role }}.jar --spring.config.location={{ platform_home_dir }}/{{ backend_name }}-{{ backend_role }}.properties
