cockroachdb_data_dir: "/var/{{ cockroachdb_product }}"
cockroachdb_log_dir: "/var/log/{{ cockroachdb_product }}"
cockroachdb_pid_dir: "/run/{{ cockroachdb_product }}"
cockroachdb_pid_file: "{{ cockroachdb_pid_dir }}/{{ cockroachdb_product }}.pid"

cockroachdb_security_mode: "secure"
